spring:
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      #默认数据库连接
      primary : master
      #格式化SQL
      p6spy: true
      druid: #以下是全局默认值，可以全局更改
        initial-size:
        max-active:
        min-idle:
        max-wait:
      datasource:
        master:
          jndi_name:  #只要配置即表示启用。
          username: root
          password: lj:Zpc#438
          driver-class-name : com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/master?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
          druid: # 以下参数针对每个库可以重新设置druid参数
            initial-size:
          #初始化脚本
          initialization-mode: always
          sql-script-encoding: utf-8
          schema: classpath:schema.sql
  #          data: classpath:schema.sql
        slave:
          one:
            jndi_name: #只要配置即表示启用。
            username: root
            password: 123456
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://127.0.0.1:3306/slave?characterEncoding=utf8&useSSL=false&serverTimezone=UT
          two:
#            jndi_name: #只要配置即表示启用。
#            username: oa
#            password: oa
#            driver-class-name : oracle.jdbc.driver.OracleDriver
#            url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
#            druid: # 以下参数针对每个库可以重新设置druid参数
#              validation-query: select 1 FROM DUAL #比如oracle就需要重新设置这个
            jndi_name: #只要配置即表示启用。
            username: root
            password: 123456
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://127.0.0.1:3306/slave?characterEncoding=utf8&useSSL=false&serverTimezone=UT
  #允许重复注册bean
  main:
    allow-bean-definition-overriding: true
  #排除原生Druid的快速配置类
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  cache:
    #ehcache配置文件路径
    ehcache:
      config: classpath:/cache/ehcache.xml
    #指定缓存类型，可加可不加
    #type: ehcache
  #缓存redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:       # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
#配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数
  supportMethodsArguments: true
  params: count=countSql
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xuaiyun.smp.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

#验证码配置
kaptcha:
  height: 50
  width: 200
  content:
    length: 4
    source: abcdefghjklmnopqrstuvwxyz23456789
    space: 2
  font:
    color: black
    name: Arial
    size: 40
  background-color:
    from: lightGray
    to: white
  border:
    enabled: true
    color: black
    thickness: 1


